### ISSUE TITLE
Unable to download csv file

### ISSUE THREAD

**Issue by Npvel** [ru-corporate/sandbox#5]
Невозможно загрузить файл, доступ либо запрещен либо страница отсутствует. Можете поделиться файлом?

**Comment by epogrebnyak** [comment]
Можете поподробнее описать проблему, в какой момент она возникает, и какой
файл вы в принципе пытаетесь создать или загрузить?

В принципе, более новая версия клиента тут, в другом репозитарии:
https://github.com/ru-corporate/boo, попробуйте там.

сб, 23 нояб. 2019 г., 16:54 Npvel <notifications@github.com>:

**Comment by Npvel** [comment]
По новому репозитарию все работает и закачивается! Огромное спасибо! Скажите а за какие периоды все это можно скачать самый ранний и самый последний? за 2018 года можно интересно или за 2000 год?

**Comment by epogrebnyak** [comment]
2012-2017 поддерживается, скорее всего есть данные за 2018 год, но я не
проверял, как работает.


Можете поэкспериментировать с 2018 и если сбоит - откройте отдельный ишью в
репозитории boo.




сб, 23 нояб. 2019 г., 17:43 Npvel <notifications@github.com>:
